### ISSUE TITLE
Strip escape codes when not attached to terminal

### ISSUE THREAD

**Issue by wtetzner** [Chris00/ANSITerminal#1]
I was wondering if ANSITerminal has support for stripping the escape codes if output is not attached to a terminal, like [Jansi](https://github.com/fusesource/jansi).

I didn't see any way to do it, but maybe I missed something.

If this isn't something ANSITerminal supports, does it sound like something that would be difficult to implement?

**Comment by Chris00** [comment]
I think we can use [Unix.isatty](https://caml.inria.fr/pub/docs/manual-ocaml-4.06/libref/Unix.html#VALisatty) to turn on/off the color codes.  (We already depend on Unix, so this is fine.)

**Comment by Chris00** [comment]
Please let me know if it fits your need (pin the package) — I'll then do a release.

**Comment by Chris00** [comment]
See https://github.com/ocaml/opam-repository/pull/10637

**Comment by wtetzner** [comment]
Wow, that was fast! Thanks!

I can't seem to get it to work, though. Maybe I pinned it wrong?

    opam pin add ANSITerminal https://github.com/Chris00/ANSITerminal.git

I'm using OPAM 2.0, so maybe that is causing an issue?

**Comment by Chris00** [comment]
The command is right for opam 1.2.  I don't know for opam 2 — haven't had time to try it much yet.  A release has been made anyway so probably can just upgrade.

**Comment by wtetzner** [comment]
Nevermind, I was using ANSITerminal.sprintf. It works great with ANSITerminal.print_string.

Thanks again.
