### ISSUE TITLE
Crashes program under CI on windows

### ISSUE THREAD

**Issue by jaredly** [Chris00/ANSITerminal#4]
the init function here https://github.com/Chris00/ANSITerminal/blob/ccfb2182da7ac391b743828bb8c00c17235bb801/src/ANSITerminal_win_stubs.c#L114 throws an error, and it's called at module load time, so there's nothing i can do to catch it.

**Comment by Chris00** [comment]
Thanks for reporting.  BTW, windows functions are undertested — I use Linux — so if you have other issues with that platform, please let me know.

**Comment by jaredly** [comment]
awesome, thanks!
